############################################################
# MUltipactor in Lower Hybrid (MULH) antenna code makefile
# AUTHOR: Manaure Francisquez
# Thayer School of Engineering
# Dartmouth College
# 14 Engineering Dr.
# Hanover, NH 03755
# USA
#
# contact email: mfrancisquez@gmail.com
#
#
#
#
# To run the code go to the directory where the makefile is.
# Then run the following commands:
# make
# LD_LIBRARY_PATH="path to executable"
# export LD_LIBRARY_PATH
# ./bin/MULH
#
# The code was developed and worked well with the gfortran compiler.
# Hasn't been tried with other compilers.
#
#
# main = main program name (currently MULHs.f90)
# mods = all the modules used
#

### USER INPUTS
cmplr = gfortran
cflags = -fPIC

# Main code running MULH
main = MULHs.f90
# Modules used (in order of independence, most independent first)
mods = precision_def.f90 constants.f90 def_types.f90 data_type.f90 \
	ecuyer_taus_rng.f90 mod_Vaughan.f90 prep_fields.f90 particle_load.f90 \
	reshape_array.f90 particle_launch.f90 p_locate.f90 inter2part.f90 \
	FIELDScalc.f90 boris.f90 random.f90 constants_NSWC.f90 \
	incomplete_gamma.f90 invincbeta.f90 reflect.f90 seem.f90 \
	particle_wall.f90 MP_detector.f90 secondary_launch.f90 multipac.f90 \
	MULHs_dec.f90

# Location of source and object files ./ being the location of make file
srcdir = ./src

### OTHERS
libname = MULHlib
executable = MULH

############################################################
maobject := $(subst .f90,.o,$(main))
mobjects := $(subst .f90,.o,$(mods))

vpath %.f90 $(srcdir):$(srcdir)/$(libname)

all: $(executable)

$(executable): $(libname)
	$(cmplr) $(srcdir)/$(main) -o $@ -L. $(libname).so
	rm -rf *.o *.mod

$(libname): $(mobjects) 
	ld -o $(libname).so $(mobjects) $(mobjects77) -shared
	LD_LIBRARY_PATH="$PWD/bin"
	export LD_LIBRARY_PATH

$(mobjects): %.o: %.f90
	$(cmplr) $(cflags) -c $< -o $@

